version: "3"
services:
  assistente-finaceiro-whatsapp-api:
    container_name: assistente_finaceiro_whatsapp_api
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    environment:
      - BACK_URL=db_admin
    volumes:
      - ../:/home/node/app:cached